module WordPairs exposing (..)


word_pairs : List ( String, String )
word_pairs =
    [ ( "r", "l" )
    , ( "rear", "real" )
    , ( "red", "led" )
    , ( "read", "lead" )
    , ( "reader", "leader" )
    , ( "appear", "appeal" )
    , ( "ravish", "lavish" )
    , ( "rude", "lewd" )
    , ( "rice", "lice" )
    , ( "right", "light" )
    , ( "row", "low" )
    , ( "ramp", "lamp" )
    , ( "fear", "feel" )
    , ( "grass", "glass" )
    , ( "raw", "law" )
    , ( "crime", "climb" )
    , ( "brink", "blink" )
    , ( "ray", "lay" )
    , ( "hear", "heal" )
    , ( "mere", "meal" )
    , ( "ear", "eel" )
    , ( "or", "all" )
    , ( "more", "mole" )
    , ( "ire", "isle" )
    , ( "mire", "mile" )
    , ( "litter", "little" )
    , ( "rock", "lock" )
    , ( "road", "load" )
    , ( "arrive", "alive" )
    , ( "correct", "collect" )
    , ( "bread", "bled" )
    , ( "froze", "flows" )
    , ( "store", "stole" )
    , ( "steer", "steel" )
    , ( "bar", "ball" )
    , ( "riddle", "little" )
    , ( "rack", "lack" )
    , ( "rook", "look" )
    , ( "Rick", "lick" )
    , ( "rise", "lies" )
    , ( "rob", "lob" )
    , ( "rump", "lump" )
    , ( "rub", "love" )
    , ( "ram", "lamb" )
    , ( "word", "world" )
    , ( "wrist", "list" )
    , ( "wired", "wild" )
    , ( "weird", "wield" )
    , ( "wear", "well" )
    , ( "whore", "whole" )
    , ( "murder", "Mulder" )
    , ( "mired", "mild" )
    , ( "race", "lace" )
    , ( "raid", "laid" )
    ]
